services:
  odoo_db_nico:
    image: postgres:16.3
    container_name: odoo_db_nico
    restart: always
    volumes:
      - type: bind
        source: ./odoo-db-data
        target: /var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - nicotina
    ports:
      - '5433:5432'

  odoo_app_nico:
    build: .
    ports:
      - '8070:8069'
    env_file:
      - .env
    container_name: odoo_app_nico
    restart: always
    depends_on:
      - odoo_db_nico
    volumes:
      - type: bind
        source: ./odoo-web-data
        target: /var/lib/odoo
      - type: bind
        source: ./config
        target: /etc/odoo
      - type: bind
        source: ./addons
        target: /mnt/extra-addons
    networks:
      - nicotina
    # command: >
      # odoo -u $ADDON_NAME -d $DB_NAME

networks:
  nicotina:

volumes:
  odoo-web-data:
  odoo-db-data: