services:
  odoo:
    build: .
    container_name: odoo-nico
    links:
      - db:db
    depends_on:
      - db
    ports:
      - '8070:8069'
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
    # command: > # Para actualizar un modulo en caso de error
    #  odoo -u <<modulo>> -d <<base de datos>>
  db:
    image: postgres:15
    container_name: db-postgres-nico
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass